### PR TITLE
fix: Support Python 3.14 where ast._Unparser was moved

### LINKED ISSUE #91: Python 3.14: `AttributeError: module 'ast' has no attribute '_Unparser'`
refactor no longer works on Python 3.14:

```pytb
Python 3.14.0 (v3.14.0:ebf955df7a8, Oct  7 2025, 08:20:14) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import refactor
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import refactor
  File "/private/tmp/refactor/refactor/__init__.py", line 4, in <module>
    from refactor.actions import *
  File "/private/tmp/refactor/refactor/actions.py", line 9, in <module>
    from refactor.ast import split_lines
  File "/private/tmp/refactor/refactor/ast.py", line 110, in <module>
    class BaseUnparser(ast._Unparser):  # type: ignore
                       ^^^^^^^^^^^^^
AttributeError: module 'ast' has no attribute '_Unparser'. Did you mean: 'unparse'?
```

3.13 is okay:

```
Python 3.13.9 (v3.13.9:8183fa5e3f7, Oct 14 2025, 10:27:13) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import refactor
>>>
```

This also prevents tools such as https://github.com/isidentical/teyit from running on Python 3.14.

### PR DESCRIPTION
**Pull request by MementoRC**
## Problem

Python 3.14 completely breaks `refactor` on import:

```
AttributeError: module 'ast' has no attribute '_Unparser'. Did you mean: 'unparse'?
```

This also breaks downstream tools like [teyit](https://github.com/isidentical/teyit).

## Root Cause

Python 3.14 moved `ast._Unparser` to a C extension module `_ast_unparse.Unparser`. The `ast.unparse()` function now lazy-imports from there:

```python
# Python 3.14 ast.py
def unparse(ast_obj):
    global _Unparser
    try:
        unparser = _Unparser()
    except NameError:
        from _ast_unparse import Unparser as _Unparser
        unparser = _Unparser()
    return unparser.visit(ast_obj)
```

## Fix

Conditional import in `refactor/ast.py`:

```python
try:
    _UnparserBase = ast._Unparser
except AttributeError:
    from _ast_unparse import Unparser as _UnparserBase
```

All internal APIs (`visit`, `traverse`, `fill`, `write`, `_indent`, `_source`) remain identical in the new location.

## Compatibility

- Python 3.10–3.13: uses `ast._Unparser` (unchanged behavior)
- Python 3.14+: uses `_ast_unparse.Unparser`

Fixes #91

### CODE REVIEW

**Comment by gforcada** [comment]
Friendly ping... is there any plan to get either this merged, or another solution that would make `refactor` and `teyit` support Python 3.14 ? 🙏🏾

**Comment by MementoRC** [comment]
@gforcada Note that we have not heard from the owner of this repo for a while (4years)
